name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]
        include:
          - os: windows-latest
            rust: stable-msvc
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
        components: rustfmt

    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose -- --nocapture
      
    # Optional: Test with different feature combinations
    - name: Test with pretty feature
      run: cargo test --features pretty --verbose
